# Generated by Django 4.1 on 2022-09-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='doc_id',
            field=models.IntegerField(),
        ),
    ]
